#!/bin/sh -e

PACKAGE="@PACKAGE@"
FILENAME="@FILENAME@"
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) \
    -a -L /usr/doc/"$PACKAGE" ]; then
	rm -f /usr/doc/"$PACKAGE"
fi

case "$1" in
  upgrade) ;;
  remove|failed-upgrade|deconfigure)
    update-alternatives --remove mpg123 "/usr/bin/$FILENAME"
    update-alternatives --remove mp3-decoder "/usr/bin/$FILENAME"
    ;;
esac
