name: CMake MSVC

on: push

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.arch }} ${{ (matrix.nasm && 'nasm') || 'msasm' }} ${{ (matrix.shared && 'shared') || 'static' }}
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        # currently windows-latest==windows-2022
        # windows-2025: VS2026
        # windows-2022: VS2022
        os: [windows-2025, windows-2022]
        arch: [x86, x64, amd64_arm64]
        # amd64_arm is only supported by older MSVC toolchains
        shared: [true, false]
        nasm: [true, false]
        exclude:
          - arch: amd6_arm64
            nasm: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ilammy/setup-nasm@v1
        if: ${{ matrix.nasm }}
      - uses: actions/checkout@v7
      - name: Setup vcvars
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.arch }}
      - name: Setup ninja
        uses: ./.github/actions/setup-ninja
      - name: CMake (configure)
        run: cmake -S ports/cmake -B build -GNinja -DUSE_ASSEMBLER=ON -DUSE_NASM=${{ matrix.nasm }} -DBUILD_SHARED_LIBS=${{ matrix.shared }}
      - name: CMake (Build)
        run: cmake --build build --verbose
