name: CMake Linux

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-26.04, ubuntu-26.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libasound2-dev libpulse-dev
    - name: Configure CMake
      run: cmake -S ports/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
