name: CMake Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, ubuntu-26.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libasound2-dev libpulse-dev
    - name: Configure CMake
      run: cmake -S ports/cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
